# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rej', models.DateTimeField(default=datetime.datetime(2016, 8, 2, 14, 7, 33, 76000))),
                ('imie', models.CharField(max_length=150, verbose_name=b'Imie')),
                ('nazwisko', models.CharField(max_length=150, verbose_name=b'Nazwisko')),
                ('kierunek', models.CharField(max_length=250, verbose_name=b'Kierunek')),
                ('telefon', models.CharField(max_length=20, verbose_name=b'Telefon')),
                ('mail', models.EmailField(max_length=254, verbose_name=b'E-mail')),
                ('lokalizacja', models.CharField(max_length=250, verbose_name=b'lokalizacja')),
                ('pytanie', models.CharField(max_length=250, verbose_name=b'Skad o nas wiesz')),
                ('rejestr', models.DateTimeField(verbose_name=b'Data rejestracji')),
            ],
        ),
        migrations.CreateModel(
            name='Stopien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name=b'Tytul')),
                ('content', models.TextField(verbose_name=b'Zawartosc')),
                ('image', models.FileField(upload_to=b'images/', verbose_name=b'Obrazek')),
            ],
        ),
        migrations.AddField(
            model_name='rejestracja',
            name='stopien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopnie.Stopien'),
        ),
    ]
